### ISSUE TITLE
More informative exceptions

### ISSUE THREAD

**Issue by realcnbs** [mbosecke/pebble#102]
Would be great to always know file and line which caused a render exceetion, currently when you get something like this:
```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
        at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:47) ~[pebble-1.6.0.jar:na]
        at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46) ~[pebble-1.6.0.jar:na]
        at com.mitchellbosecke.pebble.node.RootNode.render(RootNode.java:32) ~[pebble-1.6.0.jar:na]
        at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.buildContent(PebbleTemplateImpl.java:61) ~[pebble-1.6.0.jar:na]
        at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:107) ~[pebble-1.6.0.jar:na]
        at com.mitchellbosecke.pebble.template.PebbleTemplateImpl.evaluate(PebbleTemplateImpl.java:82) ~[pebble-1.6.0.jar:na]
....
```
You have to check all your if statements for possible wrong type. This applies to most of the exceptions I get.

**Comment by mbosecke** [comment]
Informative exceptions are one of my biggest goals but they have to be handled on a case-by-case basis. If you find any more, please let me know.

Thanks!
