### ISSUE TITLE
Malformed ternary expression fails with a cryptic NullPointerException

### ISSUE THREAD

**Issue by hectorlf** [mbosecke/pebble#160]
This expression {{ 1 > 1 ? "greater" }} fails at runtime with the following stack trace:
Caused by: java.lang.NullPointerException
    at com.mitchellbosecke.pebble.extension.escaper.EscaperNodeVisitor.escape(EscaperNodeVisitor.java:90)
    at com.mitchellbosecke.pebble.extension.escaper.EscaperNodeVisitor.visit(EscaperNodeVisitor.java:59)
    at com.mitchellbosecke.pebble.node.PrintNode.accept(PrintNode.java:47)

Didn't want to fiddle with a PR because I'm not sure if this behavior was intentional. Do you want to allow empty expressions as result operands? and do you want to allow skipping the : symbol?

**Comment by hectorlf** [comment]
Meh, I was bored at home and did a fix anyway, but with this constraints:
- no empty expressions
- colon is always required

Allowing empty expressions leads to the aforementioned NullPointerException, and, anyway, this syntax is more Java-ish.

Shall I send a PR?

**Comment by mbosecke** [comment]
Yup, I totally agree with the constraints you listed above. Send away!
