### ISSUE TITLE
Slice filter does not accept Integer for index

### ISSUE THREAD

**Issue by kodfodrasz** [mbosecke/pebble#163]
I have found a bug in the Slice filter.

But first my complaints about current Slice filter operation:
it's docs don't reflect the code. Its single argument operation is not documented.
It totally shouldn't throw exceptions when the indexes are out of range, it makes writing templates a pain, and contain lots of non idiomatic useless boilerplate.

Now about the bug:

Considering a template like this fragment:
~~~
{% if pipe.testruns | length > 1 %}
{% for test in pipe.testruns | slice(1, pipe.testruns | length) %}
<tr>
    {{ renderTestRun(test, resultClass)}}
</tr>
{% endfor %}
{%endif%}
~~~
I get the following exception:

~~~
java.lang.IllegalArgumentException: Argument toIndex must be a number. Actual type: java.lang.Integer
	at com.mitchellbosecke.pebble.extension.core.SliceFilter.apply(SliceFilter.java:62)
	at com.mitchellbosecke.pebble.node.expression.FilterExpression.evaluate(FilterExpression.java:64)
	at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:50)
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
	at com.mitchellbosecke.pebble.node.IfNode.render(IfNode.java:64)
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
	at com.mitchellbosecke.pebble.node.ForNode.render(ForNode.java:106)
	at com.mitchellbosecke.pebble.node.BodyNode.render(BodyNode.java:46)
	...
~~~
I'm using pebble version 2.0.0.

Regarding the usabiliy concerns I'd suggest a more functional streams style approach, with `skip` and `limit` filters, all returning `Iterables`, suitable for use in `for` loops (which are very cool with the `else` branches!

If interrested pls. notify me and I happily implement them, and send PR.

**Comment by mbosecke** [comment]
Thanks for the bug report; I've fixed the issues with the integer arguments.

As for the exceptions; I'm going to keep those as is for now. If I hear similar feedback from others I will reconsider.

As for the streams style approach; that sounds like a good idea. I think I'd be interested in that if you wanted to submit a PR.

**Comment by kodfodrasz** [comment]
Ok! I don't want to promise anything, but I hope I'll have some time and will do them in the next weekend. You'll notice the PR when it will be done.
